In [2]:
import torch

### **Torch Tensors**

In [3]:
# 1D Tensor
a = torch.tensor([2, 2, 1])

# 2D Tensor
b = torch.tensor([[2, 1, 4], [3, 5, 4], [1, 2, 0], [4, 3, 2]])

In [4]:
# The size of the tensors
print(a.shape)
print(b.shape)
print(a.size())
print(b.size())

torch.Size([3])
torch.Size([4, 3])
torch.Size([3])
torch.Size([4, 3])


In [5]:
c = torch.FloatTensor([[2, 1, 4], [3, 5, 4], [1, 2, 0], [4, 3, 2]])
# or we can do
# c = torch.tensor([[2, 1, 4], [3, 5, 4], [1, 2, 0], [4, 3, 2]], dtype=torch.float)

In [6]:
d = torch.DoubleTensor([[2, 1, 4], [3, 5, 4], [1, 2, 0], [4, 3, 2]])
# or we can do
# d = torch.tensor([[2, 1, 4], [3, 5, 4], [1, 2, 0], [4, 3, 2]], dtype=torch.double)

In [7]:
print(c.mean())
print(d.mean())
print(c.std())
print(d.std())

tensor(2.5833)
tensor(2.5833, dtype=torch.float64)
tensor(1.5050)
tensor(1.5050, dtype=torch.float64)


In [8]:
# Reshape b
# Note: If one of the dimensions is -1, its size can be inferred.
print(b.view(-1, 1)) # 2D, 12x1
print(b.view(12)) # 1D
print(b.view(-1, 4)) # 2D, 3x4

tensor([[2],
        [1],
        [4],
        [3],
        [5],
        [4],
        [1],
        [2],
        [0],
        [4],
        [3],
        [2]])
tensor([2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])


In [9]:
# Assign b a new shape
b = b.view(1, -1)

In [26]:
# Create a tensor with random numbers

# numbers between 0 and 1
r1 = torch.rand(4, 4)
print(r1)

# numbers taken from a normal distribution with mean 0 and variance 1
r2 = torch.randn(4, 4)
print(r2)

r2_like = torch.rand_like(r2, dtype=torch.double)
print(r2_like)

# numbers from values between 6 and 9 (exclusive of 10)
r3 = torch.randint(6, 10, (5, ))
print(r3)
print(r3.dtype)

tensor([[0.8250, 0.7701, 0.5037, 0.0440],
        [0.1334, 0.1473, 0.6698, 0.9654],
        [0.1919, 0.0200, 0.7133, 0.9215],
        [0.7472, 0.1742, 0.6076, 0.1108]])
tensor([[-0.4698, -1.3389, -1.7324, -0.6276],
        [-0.2555,  0.5492,  1.4100,  0.4525],
        [ 2.0714,  0.7245,  1.7843, -0.0947],
        [-1.3158, -1.9029, -0.9036,  0.2475]])
tensor([[0.2953, 0.6435, 0.6834, 0.6381],
        [0.2033, 0.0030, 0.4213, 0.5902],
        [0.6930, 0.1634, 0.7808, 0.0200],
        [0.6033, 0.6790, 0.5795, 0.0236]], dtype=torch.float64)
tensor([7, 9, 7, 8, 6])
torch.int64


In [21]:
# Create a 3D Tensor with 2 channels, 3 rows, and 4 columns
three_dim = torch.randn(2, 3, 4)
print(three_dim)

tensor([[[ 0.1405, -1.0496,  1.3540, -0.3124],
         [-0.9289,  0.8527,  0.6104,  1.5247],
         [ 0.4927,  0.0996,  0.6537,  0.8977]],

        [[-0.8913,  0.5585,  0.4247,  1.7875],
         [ 0.3998,  2.3096,  0.0236,  0.6760],
         [-0.6968, -1.5419,  0.2704, -0.2920]]])


In [22]:
# Get the number of elements in a tensor
print(torch.numel(three_dim))

24


In [27]:
# Create a 3x3 tensor of zeros and of dtype long
z = torch.zeros(3, 3, dtype=torch.long)
print(z)
print(z.dtype)

# Create a 3x3 tensor of ones
o = torch.ones(3, 3)
print(o)
print(o.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
torch.int64
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [31]:
# Add two tensors
# Note: Make sure they are the same size and data type.
add_result = torch.add(r1, r2)
print(add_result)

# in-place addition
r2.add_(r1)
print(r2)

tensor([[ 1.1802,  0.2013, -0.7250, -0.5397],
        [ 0.0112,  0.8439,  2.7496,  2.3833],
        [ 2.4551,  0.7644,  3.2108,  1.7483],
        [ 0.1786, -1.5545,  0.3116,  0.4691]])
tensor([[ 1.1802,  0.2013, -0.7250, -0.5397],
        [ 0.0112,  0.8439,  2.7496,  2.3833],
        [ 2.4551,  0.7644,  3.2108,  1.7483],
        [ 0.1786, -1.5545,  0.3116,  0.4691]])


In [33]:
# Indexing and Slicing
print(r2[:, 1])
print(r2[:, :2])

num = r2[2, 3]
print(num)
print(num.item())

tensor([ 0.2013,  0.8439,  0.7644, -1.5545])
tensor([[ 1.1802,  0.2013],
        [ 0.0112,  0.8439],
        [ 2.4551,  0.7644],
        [ 0.1786, -1.5545]])
tensor(1.7483)
1.7482578754425049


### **Numpy Bridge**

In [34]:
import numpy as np

In [35]:
# Convert a torch tensor to a numpy array
a = torch.ones(5)
b = a.numpy()

print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [39]:
# Note: Numpy Bridge, Whatever happens on the torch tensor also happens on the numpy array.
a.add_(1)
print(a)
print(b)

tensor([5., 5., 5., 5., 5.])
[5. 5. 5. 5. 5.]


In [40]:
# Convert a numpy array to a torch tensor
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [45]:
# Convert a list to a torch tensor
a = [2, 3, 4, 1]
b = torch.tensor(a)
print(b, b.dtype)

tensor([2, 3, 4, 1]) torch.int64


In [44]:
# Move the tensor to the GPU
# when you wanna do some GPU calculations to speed up the computations

CUDA = torch.cuda.is_available()
print(CUDA)

if CUDA:
    r2 = r2.cuda()
    print(r2)

False


### **Tensor Concatenation**

In [47]:
first_1 = torch.randn(2, 5)
second_1 = torch.randn(3, 5)
print(first_1)
print(second_1)
print('\n')

# Concatenate along the 0 dimension (i.e. concatenate rows)
con_1 = torch.cat([first_1, second_1])
print(con_1)

tensor([[ 1.2121,  0.7382,  0.0659,  1.4702,  0.2325],
        [ 0.5640,  0.4856,  0.3835, -0.4699,  0.5867]])
tensor([[-0.7882, -0.4782,  1.6111, -0.9088,  0.0425],
        [-2.0686,  0.2144,  1.3320, -2.1714,  1.0113],
        [ 0.2157, -0.5015, -0.0505,  0.5351,  0.8151]])


tensor([[ 1.2121,  0.7382,  0.0659,  1.4702,  0.2325],
        [ 0.5640,  0.4856,  0.3835, -0.4699,  0.5867],
        [-0.7882, -0.4782,  1.6111, -0.9088,  0.0425],
        [-2.0686,  0.2144,  1.3320, -2.1714,  1.0113],
        [ 0.2157, -0.5015, -0.0505,  0.5351,  0.8151]])


In [48]:
first_2 = torch.randn(2, 3)
second_2 = torch.randn(2, 5)
print(first_2)
print(second_2)
print('\n')

# Concatentate along the 1 dimension (i.e. concatenate columns)
con_2 = torch.cat([first_2, second_2], 1)
print(con_2)

tensor([[ 1.7858, -0.6263,  1.1338],
        [-2.0142,  0.5903,  1.3785]])
tensor([[-1.0393, -1.1257, -0.3789, -0.3815, -0.0351],
        [ 0.2819, -0.0121,  0.8678, -1.0244, -0.0642]])


tensor([[ 1.7858, -0.6263,  1.1338, -1.0393, -1.1257, -0.3789, -0.3815, -0.0351],
        [-2.0142,  0.5903,  1.3785,  0.2819, -0.0121,  0.8678, -1.0244, -0.0642]])


### **Adding Dimensions to Tensors**

In [50]:
# Add a dimension of 1 along a specified index
tensor_1 = torch.tensor([1, 2, 3, 4])

tensor_a = torch.unsqueeze(tensor_1, 0)
print(tensor_a)
print(tensor_a.shape)

tensor_b = torch.unsqueeze(tensor_1, 1)
print(tensor_b)
print(tensor_b.shape)

tensor([[1, 2, 3, 4]])
torch.Size([1, 4])
tensor([[1],
        [2],
        [3],
        [4]])
torch.Size([4, 1])


### **AutoGrad**

In [61]:
# Note: If requires_grad=True, the tensor object keeps track of how it was created.
x = torch.tensor([1., 2., 3.], requires_grad=True)
y = torch.tensor([4., 5., 6.], requires_grad=True)

# Check which operation was used to create the corresponding variable.
z = x + y
print(z.grad_fn)

In [62]:
s = z.sum() # the sum of all elements in z
print(s.grad_fn)

In [63]:
# If we backpropagate on s, we can find the gradients of s with respect to x.
s.backward() # compute all the gradients at once in the graph
print(x.grad) # access the gradients of s with respect to x

tensor([1., 1., 1.])


In [67]:
# By default, tensors have requires_grad = False
x = torch.randn(2, 2)
y = torch.randn(2, 2)
print(x.requires_grad, y.requires_grad)

z = x + y
# Can't backpropagate through z
print(z.grad_fn)

# Modify and set requires_grad = True
x.requires_grad_()
y.requires_grad_()

z = x + y
print(z.grad_fn)

False False
None


In [68]:
# z.detach() returns a tensor that shares the same storage as z, but with the computation history forgotten.
new_z = z.detach()
print(new_z.grad_fn) # None, because it doesn't know anything about how it was computed.

None


In [69]:
# Stop autograd from tracking history on tensors
print(x.requires_grad)
print((x+10).requires_grad)
with torch.no_grad():
    print((x+10).requires_grad)

True
True
False


In [71]:
### EXAMPLE
x = torch.ones(2, 2, requires_grad=True)
print(x)

y = x + 2
print(y)
print(y.grad_fn)

z = y * y * 3
out = z.mean()
print(z)
print(out)
print('\n')

out.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
